upload:
  path: D:/LearnMap/LearnMapUploads
spring:
  web:
    resources:
      static-locations: file:${upload.path},classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB      # 限制上传文件大小
      max-request-size: 10MB