spring.datasource.url=JDBC:mysql://localhost:3306/learnmap?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=YRF041106mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

zhipu.api.key=bd5102dd4b7e4f539e1f9f6ba2cf8504.HDVoUP64CY19RRee